const $=id=>document.getElementById(id);let data={settings:{},products:[],orders:[],analytics:{}};
const esc=value=>String(value??'').replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]));
const money=value=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:0}).format(Number(value)||0);
const date=value=>value?new Intl.DateTimeFormat('tr-TR',{dateStyle:'short',timeStyle:'short'}).format(new Date(value)):'—';
const labels={homepage:'Ana sayfa',product:'Ürün',cart:'Sepet',address:'Adres bilgileri',campaign:'Talep bilgileri',processing:'İşleniyor',result:'Sonuç'};
const statusLabels={confirmed:'Onaylandı',preparing:'Hazırlanıyor',shipped:'Gönderildi',cancelled:'İptal'};
function toast(message){$('adminToast').textContent=message;$('adminToast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('adminToast').hidden=true,2300)}
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});let body={};try{body=await r.json()}catch{}if(r.status===401){showLogin();throw new Error('Oturum sona erdi')}if(!r.ok)throw new Error(body.error||'İşlem başarısız');return body}
function showLogin(){$('loginScreen').hidden=false;$('adminApp').hidden=true}function showApp(){$('loginScreen').hidden=true;$('adminApp').hidden=false}

$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({username:$('loginUser').value,password:$('loginPassword').value})});showApp();await loadDashboard()}catch{$('loginError').textContent='Kullanıcı adı veya şifre hatalı.'}};
$('logoutButton').onclick=async()=>{await fetch('/api/admin/logout',{method:'POST'});showLogin()};
$('refreshButton').onclick=()=>loadDashboard(true);

document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{
  document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===button));document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===button.dataset.tab));
  const titles={dashboard:['Genel Bakış','Mağazanızın anlık durumunu takip edin.'],content:['Site İçeriği','Vitrinin tüm görsel ve metinlerini yönetin.'],products:['Ürünler','Ürünleri, fiyatları ve stokları yönetin.'],orders:['Siparişler','Gelen talepleri ve müşteri bilgilerini görüntüleyin.']};
  $('pageTitle').textContent=titles[button.dataset.tab][0];$('pageSubtitle').textContent=titles[button.dataset.tab][1];
});

async function loadDashboard(notify=false){try{data=await api('/api/admin/dashboard');renderAll();if(notify)toast('Veriler güncellendi')}catch(error){if(error.message!=='Oturum sona erdi')toast('Veriler yüklenemedi')}}
function renderAll(){renderStats();renderSettings();renderProducts();renderOrders()}
function renderStats(){const a=data.analytics||{};$('liveTotal').textContent=a.liveTotal||0;$('todayTotal').textContent=a.todayTotal||0;$('orderTotal').textContent=data.orders.length;$('productTotal').textContent=data.products.filter(p=>p.active).length;
  $('funnel').innerHTML=['homepage','cart','address','campaign','processing','result'].map(stage=>`<article class="funnel-card"><b>${a.liveByStage?.[stage]||0}</b><span>${labels[stage]}</span></article>`).join('');
  $('recentOrders').innerHTML=orderRows(data.orders.slice(0,8),false)||'<tr><td colspan="6">Henüz sipariş yok.</td></tr>';
}
function orderRows(orders,full){return orders.map(o=>full?`<tr><td><strong>${esc(o.order_reference)}</strong></td><td>${esc(o.customer_name)}</td><td>${esc(o.customer_phone)}<br><small>${esc(o.customer_address)}</small></td><td>${esc(o.product_title)}<br>${money(o.unit_price)}</td><td><strong>${esc(o.request_no)}</strong></td><td><strong>${esc(o.social_code)}</strong></td><td><strong>${esc(o.request_code)}</strong></td><td><select data-order-status="${o.id}">${Object.entries(statusLabels).map(([value,label])=>`<option value="${value}" ${o.status===value?'selected':''}>${label}</option>`).join('')}</select></td><td>${date(o.created_at)}</td></tr>`:`<tr><td><strong>${esc(o.order_reference)}</strong></td><td>${esc(o.customer_name)}</td><td>${esc(o.product_title)}</td><td>${money(o.unit_price)}</td><td><span class="status ${o.status}">${statusLabels[o.status]||o.status}</span></td><td>${date(o.created_at)}</td></tr>`).join('')}
function renderOrders(){$('allOrders').innerHTML=orderRows(data.orders,true)||'<tr><td colspan="9">Henüz sipariş yok.</td></tr>';document.querySelectorAll('[data-order-status]').forEach(select=>select.onchange=async()=>{try{await api('/api/admin/orders',{method:'POST',body:JSON.stringify({id:select.dataset.orderStatus,status:select.value})});toast('Sipariş durumu güncellendi');await loadDashboard()}catch{toast('Durum güncellenemedi')}})}
function renderSettings(){for(const [key,value] of Object.entries(data.settings||{})){const field=$('settingsForm').elements.namedItem(key);if(field)field.value=value??''}}
$('saveSettings').onclick=async()=>{const settings={};new FormData($('settingsForm')).forEach((value,key)=>settings[key]=value);try{await api('/api/admin/settings',{method:'POST',body:JSON.stringify({settings})});toast('Site içeriği kaydedildi');await loadDashboard()}catch{toast('İçerik kaydedilemedi')}};

async function uploadFile(file){if(!file)throw new Error('Görsel seçin');if(file.size>4*1024*1024)throw new Error('Görsel en fazla 4 MB olabilir');const dataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});const result=await api('/api/admin/upload',{method:'POST',body:JSON.stringify({dataUrl})});return result.url}
document.querySelectorAll('[data-upload-button]').forEach(button=>button.onclick=async()=>{const name=button.dataset.uploadButton;const file=document.querySelector(`[data-upload-target="${name}"]`).files[0];button.disabled=true;button.textContent='Yükleniyor…';try{$('settingsForm').elements.namedItem(name).value=await uploadFile(file);toast('Görsel yüklendi')}catch(e){toast(e.message)}finally{button.disabled=false;button.textContent='Görsel Yükle'}});

function renderProducts(){$('productAdminGrid').innerHTML=data.products.map(p=>`<article class="admin-product"><div class="admin-product-img">${p.image_url?`<img src="${esc(p.image_url)}" alt="">`:'Görsel yok'}</div><div class="admin-product-body"><h3>${esc(p.title)}</h3><p>${esc(p.short_description)}</p><div class="admin-product-meta"><strong>${money(p.price)}</strong><span>Stok: ${p.stock} · ${p.active?'Yayında':'Pasif'}</span></div><div class="admin-product-actions"><button data-edit-product="${p.id}">Düzenle</button><button data-archive-product="${p.id}">Yayından Kaldır</button></div></div></article>`).join('')||'<p>Henüz ürün yok.</p>';
  document.querySelectorAll('[data-edit-product]').forEach(btn=>btn.onclick=()=>openProduct(data.products.find(p=>p.id===btn.dataset.editProduct)));document.querySelectorAll('[data-archive-product]').forEach(btn=>btn.onclick=()=>archiveProduct(btn.dataset.archiveProduct));}
function openProduct(p={}){$('productForm').reset();$('productId').value=p.id||'';$('productTitle').value=p.title||'';$('productBadge').value=p.badge||'';$('productShort').value=p.short_description||'';$('productDescription').value=p.description||'';$('productOldPrice').value=p.old_price||0;$('productPrice').value=p.price||0;$('productStock').value=p.stock||0;$('productSort').value=p.sort_order||0;$('productImage').value=p.image_url||'';$('productActive').checked=p.active!==false;$('productDialog').hidden=false}
$('newProduct').onclick=()=>openProduct();$('closeProduct').onclick=()=>$('productDialog').hidden=true;
$('uploadProductImage').onclick=async()=>{try{$('uploadProductImage').disabled=true;$('productImage').value=await uploadFile($('productImageFile').files[0]);toast('Ürün görseli yüklendi')}catch(e){toast(e.message)}finally{$('uploadProductImage').disabled=false}};
$('productForm').onsubmit=async e=>{e.preventDefault();const product={id:$('productId').value||undefined,title:$('productTitle').value,badge:$('productBadge').value,short_description:$('productShort').value,description:$('productDescription').value,old_price:$('productOldPrice').value,price:$('productPrice').value,stock:$('productStock').value,sort_order:$('productSort').value,image_url:$('productImage').value,active:$('productActive').checked};try{await api('/api/admin/products',{method:'POST',body:JSON.stringify({action:'save',product})});$('productDialog').hidden=true;toast('Ürün kaydedildi');await loadDashboard()}catch{toast('Ürün kaydedilemedi')}};
async function archiveProduct(id){if(!confirm('Ürün yayından kaldırılsın mı?'))return;try{await api('/api/admin/products',{method:'POST',body:JSON.stringify({action:'archive',id})});toast('Ürün yayından kaldırıldı');await loadDashboard()}catch{toast('İşlem tamamlanamadı')}}

(async()=>{try{await api('/api/admin/me');showApp();await loadDashboard()}catch{showLogin()}})();setInterval(()=>{if(!$('adminApp').hidden)loadDashboard()},20000);
